### ISSUE TITLE
Scaling of equations and variables

### ISSUE THREAD

**Issue by hhoeschle** [chkwon/PATHSolver.jl#10]
Hallo, 

I am using your julia package and have moved from GAMS to julia recently. I really appreciate your work. However, there is one part I am missing, or maybe haven't found yet:

In order to avoid poorly scaled models, GAMS offers the possibility to scale individual equations or variables (described a.o. on page 48 of the PhD Todd Munson, also here https://gams.com/help/index.jsp?topic=%2Fgams.doc%2Fuserguides%2Fmccarl%2Fscale.htm). 

I have achieved very good improvements in times of computation time using this. I was wondering if this is possible within Julia and the PathSolver/Complementary/ JuMP framework.

Thanks again for your work

**Comment by chkwon** [comment]
Glad that my package is helpful for you. 

@mlubin Any thought on scaling on JuMP?

**Comment by mlubin** [comment]
Happy to help out but no plans to implement this myself.

**Comment by chkwon** [comment]
@mlubin So there is currently no support for scaling in JuMP, right?

**Comment by mlubin** [comment]
Correct, JuMP does not do rescaling of any kind. We typically expect the
solver to be responsible for this.

On Nov 3, 2016 08:34, "Changhyun Kwon" notifications@github.com wrote:

@mlubin https://github.com/mlubin So there is currently no support for
scaling in JuMP, right?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/chkwon/PATHSolver.jl/issues/10#issuecomment-258178508,
or mute the thread

**Comment by chkwon** [comment]
@hhoeschle It seems that user's direct control on scaling is the best option for now, both for JuMP and  others. 

Since this PATHSolver.jl is a simple wrapper of the PATH solver, I don't think scaling will kick in. But I'll keep this in mind for other parts like Complementarity.jl.

**Comment by chkwon** [comment]
@hhoeschle By the way, could you tell me what kind of problems have you solved using PATHSolver and Complementarity?

**Comment by hhoeschle** [comment]
I typically solve Market Equilibrium Models. You can find a example paper here: http://dx.doi.org/10.1109/PSCC.2016.7540839

One of the scaling issues typically occurs if I introduce a renewable energy source target which is defined over all hours of the year while other constraints are defined on hourly basis. As a result, the constraints differ by a factor of 1000 to 10000 . 

Without scaling the PATH solver log looks as follows:

> INITIAL POINT STATISTICS
> Zero row of order . . . . . . .  0.0000e+000 eqn: (f[ 3138])
> Zero row of order . . . . . . .  0.0000e+000 eqn: (f[ 3378])
> Zero row of order . . . . . . .  0.0000e+000 eqn: (f[ 3618])
> Zero row of order . . . . . . .  0.0000e+000 eqn: (f[ 3858])
> Zero row of order . . . . . . .  0.0000e+000 eqn: (f[ 4098])
> Zero row of order . . . . . . .  0.0000e+000 eqn: (f[ 4338])
> Zero row of order . . . . . . .  0.0000e+000 eqn: (f[ 4578])
> Zero row of order . . . . . . .  0.0000e+000 eqn: (f[ 4818])
> Zero row of order . . . . . . .  0.0000e+000 eqn: (f[ 5058])
> Zero row of order . . . . . . .  0.0000e+000 eqn: (f[ 5298])
> Total zero rows . . . . . . . .  10
> Maximum of X. . . . . . . . . .  0.0000e+000 var: (x[    1])
> Maximum of F. . . . . . . . . .  3.4286e+007 eqn: (f[  481])
> Maximum of Grad F . . . . . . .  1.9998e+003 eqn: (f[ 3133])
>                                             var: (x[ 1923])
> 
> INITIAL JACOBIAN NORM STATISTICS
> Maximum Row Norm. . . . . . . .  2.5438e+003 eqn: (f[ 1923])
> Minimum Row Norm. . . . . . . .  1.0000e+000 eqn: (f[  722])
> Maximum Column Norm . . . . . .  2.5418e+003 var: (x[ 1923])
> Minimum Column Norm . . . . . .  1.0000e+000 var: (x[  722])

After scaling in GAMS, the output looks as follows:

> INITIAL POINT STATISTICS
> Maximum of X. . . . . . . . . .  0.0000e+000 var: (lambda_em(1,1))
> Maximum of F. . . . . . . . . .  3.4286e+007 eqn: (RES_target_lamba_res(1))
> Maximum of Grad F . . . . . . .  6.0125e+001 eqn: (KKT_ls_em(1,169))
>                                             var: (lambda_em(1,169))
> 
> INITIAL JACOBIAN NORM STATISTICS
> Maximum Row Norm. . . . . . . .  6.0125e+001 eqn: (KKT_ls_em(1,169))
> Minimum Row Norm. . . . . . . .  4.7900e-001 eqn: (KKT_cap(5))
> Maximum Column Norm . . . . . .  6.3131e+001 var: (lambda_em(1,174))
> Minimum Column Norm . . . . . .  4.7900e-001 var: (cap(5))

By the way, it would also be nice if JuMP could forward the names as GAMS does.

What do you exactly mean by "direct control on scaling"? Do you think something like `complements(mode, equation_x/1000., x)` would work?

**Comment by chkwon** [comment]
The name forwarding needs to be done between Complementarity.jl and the PATH Solver. Nothing's to do with JuMP. I'll add this to my to do list.

`complements(mode, equation_x/1000., x)` This does not work. 

I meant scaling in the formulation / modeling stage, before coding it in Julia.

**Comment by chkwon** [comment]
@hhoeschle The latest version (v0.1.0) of [Complementarity.jl](https://github.com/chkwon/Complementarity.jl) now supports variable name forwarding. But not yet the names for complementary functions.

**Comment by chkwon** [comment]
@hhoeschle The latest version (v0.2.0) of Complementarity.jl now supports **mapping** name forwarding. Please update the package and let me know how it goes. Please note that the new version of Complementarity.jl uses new syntax. 

```julia
using Complementarity, JuMP
m = MCPModel()
@variable(m, x >= 0)
@mapping(m, F, x+2)
@complementarity(m, F, x)
status = solveMCP(m)
@show getvalue(x)
```

**Comment by hhoeschle** [comment]
@chkwon I am currently running some experiments with the previous version which involves also logging of computation time . I would like to postpone the update until I will finish all runs in order to  avoid biased results.. I will definitely update and provide feedback afterwards.

**Comment by chkwon** [comment]
@hhoeschle No rush!!
