### ISSUE TITLE
Huge overhead using JuMP

### ISSUE THREAD

**Issue by vepiteski** [chkwon/PATHSolver.jl#121]
When solving large LCP models using JuMP, I observe a huge overhead. Here is an example, the LCP is the Murty model.

> `using PATHSolver
> using LinearAlgebra
> using Complementarity
> 
> MA=2.0*ones(n,n)
> M=tril(MA,-1) + I
> 
> x=zeros(n)
> q = vec(-ones(n,1))
> 
> mJuMP = Model(PATHSolver.Optimizer)
> @variable(mJuMP, x[1:n] >= 0)
> @constraint(mJuMP, M * x .+ q ⟂ x)
> 
> @time optimize!(mJuMP)
> `

Its output trailer is as follows for n=1024

> `Total Time. . . . . . . **0.018557**
> Residual. . . . . . . . 0.000000e+00
> Postsolved residual: 0.0000e+00
>
>   **5.496285** seconds (12.75 k allocations: 68.493 MiB)
> `

As you may observe, @time returns 5.49 seconds and PATH itself needed 0.02 seconds. The overhead is much worse for larger models, for instance, for n=2048, @time returns 109.05 seconds  but  PATH itself reports 0.06 seconds. Actually, one has to wait that long before PATH begins its execution.

**Comment by odow** [comment]
Fix is in https://github.com/chkwon/PATHSolver.jl/pull/122. I'll get a new release today.
