### ISSUE TITLE
Error: Missing Function path_main

### ISSUE THREAD

**Issue by hhoeschle** [chkwon/PATHSolver.jl#13]
Hi,

since the most recent update I get the following error when I try to solve a MCP using the PATH solver:

`ERROR: LoadError: ccall: could not find function path_main in library libpath47julia
 in solveMCP(::Function, ::Complementarity.#myjac#3{JuMP.Model}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{String,1}, ::Ptr{Void}) at C:\Users\hhoschle\.julia\v0.5\PATHSolver\src\PATHSolver.jl:63
 in _solve_path(::JuMP.Model) at C:\Users\hhoschle\.julia\v0.5\Complementarity\src\mcp.jl:164
 in #solveMCP#1(::Symbol, ::Symbol, ::Function, ::JuMP.Model) at C:\Users\hhoschle\.julia\v0.5\Complementarity\src\mcp.jl:94 `

I run the model on a Windows 7  64bit.
- Complementarity               0.1.0
- JuMP                          0.15.1
- PATHSolver                    0.1.0

I have already tried to rebuild the package but this did not help.

Any ideas, recommendations? More information needed?

Thank you

**Comment by chkwon** [comment]
Could you try to remove PATHSolver and reinstall?

**Comment by chkwon** [comment]
@hhoeschle Did it work?

**Comment by hhoeschle** [comment]
@chkwon I have tried the following:

Trying to rebuild using Pkg.build("PATHSolver") -> no success

Remove the folder PATHSolver from .julia/v0.5/PathSolver ( Pkg.rm("PATHSolver") did not work )
followed by a Pkg.update() to reinstall -> success

It seems to work again. Note, I had the same issue on a ubuntu machine.

Thank you

**Comment by hhoeschle** [comment]
@chkwon 2 comments on the build of PATHSolver:
- julia needs to be accessible in the path and needs to point to the correct julia version in which you want to build the package. I used an alias  'julia5' to point to julia version 0.5 which caused some problem during the build.
- I also had my .juliarc switch the current working directory which caused an error as the test.jl could not be found. 

Maybe it helps to improve the package. I really appreciate your work.

**Comment by chkwon** [comment]
Thanks a lot for the detailed comments. I think I know how to handle this. It will be improved.
