### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by hhoeschle** [chkwon/PATHSolver.jl#15]
Hallo,

I get the following errors for a model that I have transferred from GAMS to julia. GAMS together with the PATH solver returns a solution for the model. 

However, julia exits to an error. Moreover, the error changes with model parameters. I have invested quite some time in checking that I have not made a mistake in the transfer. I am a bit stuck here.

Unfortunately, the error messages are not that rich:

```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7fee72ca5d0 -- Memory_Default at C:\Users\hhoschle\.julia\v0.5\PATHSolver\deps\usr\lib\path47.dll (unknown line)
while loading C:\PhD\journals\2017_interconnected_cm\julia\model/dev_model.jl, in expression starting on line 923
Memory_Default at C:\Users\hhoschle\.julia\v0.5\PATHSolver\deps\usr\lib\path47.dll (unknown line)
unknown function (ip: 000000002964203F)
Allocations: 250906427 (Pool: 250895190; Big: 11237); GC: 885
```

another error:

```
    1     1  1819   267 3.6891e+007  1.0e+000    1.0e+001 (RES_target_lambda_res[s)
    2     2  5467  1819 3.3916e+007  1.0e+000    9.0e+000 (RES_target_lambda_res[s)
    3     5  3884  5734 3.2877e+007  6.4e-001    8.1e+000 (RES_target_lambda_res[s)
    4     6   576  5728 2.8918e+007  1.0e+000    7.3e+000 (RES_target_lambda_res[s)
    5     7  1194  5377 2.6426e+007  1.0e+000    6.6e+000 (KKT_res_certs[s001,BE,W)
    6     8   139  4206 2.3117e+007  1.0e+000    5.9e+000 (KKT_res_certs[s001,BE,W)
    7    12     2  4070 2.1072e+007  4.1e-001    5.3e+000 (KKT_res_certs[s001,BE,W)
pn_search terminated: no basis change.
  ** WARNING **
Basis modifications: 4759

Major Iteration Log
major minor  func  grad  residual    step  type prox    inorm  (label)
    0     0    13     8 2.1072e+007           I 4.8e+000 8.5e+006 (KKT_res_certs[s)
  ** SOLVER ERROR **
Too small.
```

If I can somehow overcome this problem, I would be really thankful. If I need to provide more information, please let me know.

**Comment by chkwon** [comment]
Not sure what to do, especially for the first error. 

I was wondering if you have obtained the same solutions from GAMS and Julia before. There might be some errors when I convert JuMP model to PATH model.

**Comment by hhoeschle** [comment]
after some testing I now think that the 2 errors are not caused by the same thing:

on the first error (EXCEPTION_ACCESS_VIOLATION)
I have tried several things and the error does not occur anymore, but I cannot provide a final answer what caused the problem in the first place.
- In my model I use some penalty terms with large penalty factors. In the original version I wrote them like 
`PENALTY_FACTOR = 1e10` then I have tried the same with `PENALTY_FACTOR = 100000000000.` I have replaced several penalty factors with the float-like typesetting. Maybe this caused a problem in the interface with the C implementation of PATH? I lack experience with C but the error description points towards C/C++ 
-  Unfortunatly, I have also rebuild the PATHSolver in the meantime, so it could also be this.
- I will try to reproduce the error and further investigate the issue, but I think the first bullet is something worth investing some time in.

on the second error (difference with GAMS)
the reason why the solver with julia can not return a solution is linked to the scaling. In my GAMS implementation, I make use of the possibility to scale constraints and variables, e.g.
```
it.scaleopt = 1;
Limit_cs_1_mu_cs_1.scale = 10000;
mu_cs_1.scale = 1/10000;
```
see also https://www.gams.com/latest/docs/userguides/mccarl/scaling_gams_models.htm

Disabling the scaling in my GAMS implementation also  gets the solver stuck and it does not return a solution.
If you compare the following lines in the log file you can see the difference:

with scaling of multiple constraints and variables:
- norms are all in the same range
- PATH returns solution
```
INITIAL JACOBIAN NORM STATISTICS
Maximum Row Norm. . . . . . . .  5.6610e+001 eqn: (KKT_cap(3))
Minimum Row Norm. . . . . . . .  1.0000e+000 eqn: (KKT_cs_1)
Maximum Column Norm . . . . . .  9.5072e+001 var: (lambda_em(43,7))
Minimum Column Norm . . . . . .  1.0000e+000 var: (ls_em(1,1))
```

without scaling:
- norms are not in the same range
- PATH does not return a solution
- https://www.gams.com/24.8/docs/solvers/path/index.html#PATH_POORLY_SCALED_MODELS
```
INITIAL JACOBIAN NORM STATISTICS`
Maximum Row Norm. . . . . . . .  3.6393e+004 eqn: (Limit_cs_1_mu_cs_1)
Minimum Row Norm. . . . . . . .  1.0000e+000 eqn: (KKT_cs_1)
Maximum Column Norm . . . . . .  3.6393e+004 var: (mu_cs_1)
Minimum Column Norm . . . . . .  1.0000e+000 var: (ls_em(1,1))
```

For now, I don't see how this could be implemented in julia, but the example shows that it can make a difference. Having a result or not.

I have experimented a bit with manually scaling:
`@mapping(model, KKT_dem_ccm_upp[s in scenarios, m in markets_ccm],`
`            (+ mu_dem_ccm_upp[s,m]`
`            - 0.5 * (PRICE_CAP_CCM[s,m] - lambda_ccm_upp[s,m]) * mu_cs_ccm_upp[s,m]`
`            + beta_ccm_upp[s,m]`
`            ) * 1e-4)`
`        @complementarity(model, KKT_dem_ccm_upp, dem_ccm_upp)`

this already scales the constraint, but I have not found a way to scale the variable, unfortunately.
ideally, we could come up with something like
`@complementarity(model, F, var, scale_F=1, scale_var=1)`
with 2 additional optional parameters

looking forward to your answer

**Comment by chkwon** [comment]
For the first error, which one worked? `1e10` or `10000000000`?

For the second error, I am glad that you were able to figure out. I just need to implement scaling. This will take long time though.

**Comment by hhoeschle** [comment]
I could avoid errors by using `10000000000.` including the `.`

**Comment by chkwon** [comment]
closing for the new version of the package
