### ISSUE TITLE
Allow for manually setting number of non-zero jacobian elements

### ISSUE THREAD

**Issue by chrished** [chkwon/PATHSolver.jl#29]
I ran into the issue that the initial Jacobian has fewer non-zero elements than whatever comes up during iterations. This only requires few lines of code changes, e.g. via calling with a named argument where a user can provide the number of non-zero elements and otherwise default to the current setup.

**Comment by chkwon** [comment]
Can you provide an example?

**Comment by chrished** [comment]
I got this issue as part of a large problem, I will try to make a smaller example function to illustrate. 

As to the solution: I copied your code some time ago and made the changes I was looking for (https://github.com/chrished/PATH2.jl). 

Will get back to you with an example for the problem!

**Comment by chrished** [comment]
here an example where I get the error: 
https://github.com/chrished/PATH2.jl/blob/master/test/example_fail.jl

I tried to make a more concise example, but failed unfortunately. Anyway, as soon as some equations depend on each other only for a range of parameters one gets a Jacobian with different number of non-zero elements depending on the current parameters. Does that make sense?
