### ISSUE TITLE
disable output completely

### ISSUE THREAD

**Issue by aharoun** [chkwon/PATHSolver.jl#34]
I wonder if it is possible to kill the output completely when using `solveLCP`. Even with `options(output=:no)`, it prints some results. I suspect printing options are embedded in the source library and one may not have access to it, still wanted to ask.

**Comment by chkwon** [comment]
Indeed they are from the source library. 

You may try something like
```julia
rd, wr = redirect_stdout()
for i=1:10
	z, f = solveMCP(myfunc, lb, ub)
end
close(rd)
close(wr)
```
But I'm not sure how I can recover the original `stdout`.

**Comment by aharoun** [comment]
Thanks! Actually I tried something similar but couldn't succeed.

**Comment by arnavs** [comment]
I've been using `Suppressor` for this. 

```
arg1, arg2, arg3, ... = @suppress solveLCP(args...)
```

**Comment by chkwon** [comment]
@arnavs This is cool! Thanks!
