### ISSUE TITLE
Error in version v0.6, v0.6.2 works

### ISSUE THREAD

**Issue by chrished** [chkwon/PATHSolver.jl#46]
The version v0.6 gives the error described in this issue: https://github.com/chkwon/PATHSolver.jl/issues/42

However, just switching to v0.6.2 makes this issue disappear. For other who may encounter the issue: could the Readme be changed to include this line instead:

```julia
Pkg.add(Pkg.PackageSpec(name = "PATHSolver", version = v"0.6.2"))
```

Thanks!

**Comment by chkwon** [comment]
Thanks! Updated README.
