### ISSUE TITLE
Non linear problems

### ISSUE THREAD

**Issue by davidanthoff** [chkwon/PATHSolver.jl#47]
I'm trying to use PATHSolver with JuMP for non linear problems, but when I add a non linear constraint, I get an error message saying that the solver doesn't support non linear problems.

My understanding is that the underlying PATH solver of course does support non linear problems, so I'm wondering whether I just need to do something slightly different, or whether this is just not yet exposed via JuMP?

**Comment by odow** [comment]
This isn't exposed via JuMP due to some internal JuMP issues. 

You'll have to use the low-level interface:
https://github.com/chkwon/PATHSolver.jl/blob/6d8c668b4b9c1627df13a8a79b4c1d0f0c56cee4/src/C_API.jl#L418-L454

**Comment by davidanthoff** [comment]
Thanks for clarifying this!

Is there some more specific information what would have to be done to make this work with JuMP? Or do you know whether anyone is working on that? Is it some principle design problem, or is it that simply no one has done the work to implement this yet?

Back in the days I was pretty familiar with MathProgBase.jl, so if there is just a small delta to be done, I might take a crack.

**Comment by odow** [comment]
It's a principle design problem, because we have no way of modeling `NonlinearFunction`-in-`Set`. (We can only do `l <= nonlinear(x) <= u`.)

This is something that cannot be resolved short of a rewrite of JuMP's NLP support. Here's some of the backstory with possible plans: https://github.com/jump-dev/MathOptInterface.jl/issues/846

**Comment by davidanthoff** [comment]
I think we can solve this, given that Complementarity.jl works great for now.
