### ISSUE TITLE
Can we hide the options reading output somehow?

### ISSUE THREAD

**Issue by davidanthoff** [chkwon/PATHSolver.jl#52]
Right now there is always an output like this:
```
Reading options file /var/folders/bg/dzq_hhvx1dxgy6gb5510pxj80000gn/T/tmpiSsCRO
Read of options file complete.
```
I think that is printed by PATH itself, right? Is there some option that we could flip so that this isn't shown by PATH? Would be nice if we could disable printing that particular message.

**Comment by chkwon** [comment]
Yes, this is by PATH.  I'm not sure what can be done for this. Perhaps it's possible to suppress all messages. I don't think it's possible to hide only particular messages though.

**Comment by lassepe** [comment]
Fwiw, in the C-API it should be sufficient to just pass `silent = true` to `solve_mcp` 
https://github.com/chkwon/PATHSolver.jl/blob/8159282ff8318c4b5e7353fab0e02ed1f48a7e85/src/C_API.jl#L559

**Comment by odow** [comment]
Closing because `silent = true` is the correct solution.
