### ISSUE TITLE
Tag a version

### ISSUE THREAD

**Issue by davidanthoff** [chkwon/PATHSolver.jl#60]
Could a version that is compatible with MOI 0.10 be tagged? CC @odow Thanks :)

**Comment by odow** [comment]
https://github.com/JuliaRegistries/General/pull/55413

**Comment by davidanthoff** [comment]
@odow Thanks! Right now auto-merge is blocked because version 1.2.0 was skipped. Are we ok with that? I can merge things in the registry, so if you give me an OK that you just want to skip 1.2, I'll merge the PR over there. I don't think that can cause any problems.

**Comment by odow** [comment]
Oh. I didn't realize I didn't tag v1.2

**Comment by odow** [comment]
I've changed to v1.2: https://github.com/chkwon/PATHSolver.jl/commit/e565bf5ec86eb76e76e01f9a739b2032de0d4d70 so I'll see if JuliaRegistrator will be happy if I update it.

**Comment by odow** [comment]
It opened https://github.com/JuliaRegistries/General/pull/55423, so let's just close https://github.com/JuliaRegistries/General/pull/55413?

**Comment by davidanthoff** [comment]
Yep, perfect! I closed the 1.3.0 PR, and the 1.2.0 was just merged :)
