### ISSUE TITLE
PATHSolver doesn't build on  aarch64-apple-darwin

### ISSUE THREAD

**Issue by MichelJuillard** [chkwon/PATHSolver.jl#61]
PATHSolver depends on DataDeps. DataDeps depends upon BinaryProvider and BinaryProvider doesn't build on aarch64-apple-darwin.
See https://discourse.julialang.org/t/m1-mac-faile-to-install-binaryprovider-package/74103/2 and https://github.com/oxinabox/DataDeps.jl/issues/152

**Comment by odow** [comment]
PATHSolver.jl doesn't support M1, and this is unlikely to change until Prof. Ferris updates PATH to M1. Use Rosetta instead.

**Comment by andresdrenik** [comment]
Is there any update on this?

**Comment by odow** [comment]
No update. We need an upstream version from https://pages.cs.wisc.edu/~ferris/path.html. Use the Rosetta build of Julia.

**Comment by odow** [comment]
To clarify for Rosetta:

Download and install the "macOS x86 (Intel or Rosetta)" build of Julia from https://julialang.org/downloads/. Then PATH will work fine.

If you're using juliaup, you want to install the `lts~x64` version.

**Comment by odow** [comment]
Discussed with the PATH folks. It's on their long-term roadmap to provide binaries for M1, but there is no ETA. In the meantime, use Rosetta.
