### ISSUE TITLE
Global state?

### ISSUE THREAD

**Issue by lassepe** [chkwon/PATHSolver.jl#71]
During my hunt for  #70 I noticed some weird behavior which looks to me like PATH has some global state either in C or in Julia. Specifically, the #70 only showed up if I solve another specific MCP before it. I suspect that some solver object is not fully reset leading to this interdependence between solves. I'm calling the solver through the MCP C-api so I wouldn't expect any side-effects between calls as I'm not carrying over any solver object. This issue is part of the reason why I cannot give a compact reproducer for #70 -- it only shows up if I run my research code in a specific sequence.

**Comment by odow** [comment]
Closing in favor of #70. We don't need two issues to track this.
